### ISSUE TITLE
How to Enable/Disable DDIO？

### ISSUE THREAD

**Issue by sunce4t** [aliireza/ddio-bench#3]
Hi，thanks for your code，I am tring to enable/disable DDIO using your code. However，I meet some problem.
sudo ./change-ddio 

\========================
0000:97:02.0 vendor=8086 device=347a class=0604 irq=136 (pin 0) base0=39bffff00004 
 (Device 347a)
\========================
-----befrore change-----
perfctrlsts_0 val: 0x1901000b
NoSnoopOpWrEn val: 0x8
Use_Allocating_Flow_Wr val: 0x0
DDIO is enabled!
-----after change-----
perfctrlsts_0 val: 0x1901000b
NoSnoopOpWrEn val: 0x8
Use_Allocating_Flow_Wr val: 0x0

That is, when I call the ddio_enable() or ddio_disable() function, the register never change.

and below are infomations about my server:
Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz

lspci | grep Mel 
98:00.0 Ethernet controller: Mellanox
so the nic_bus is 0x98
Hope to get your help!

**Comment by aliireza** [comment]
Hi, 

I have not tested this on IceLake architecture, so the registers might have changed. You can try to find the datasheet and double check the addresses/offsets.

**Comment by sunce4t** [comment]
thanks！
